name: 'Custom Kernel Configs'
description: 'Custom kernel configuration options'

runs:
  using: "composite"
  steps:
    - name: Enable Custom Kernel Configs
      uses: ./.github/actions/set-kernel-config
      with:
        config_list: |
          # CAN Bus
          CONFIG_CAN=y
          CONFIG_CAN_RAW=y
          CONFIG_CAN_BCM=y
          CONFIG_CAN_GW=y

          # IIO / PCI Endpoint ConfigFS
          CONFIG_IIO_CONFIGFS=y
          CONFIG_PCI_ENDPOINT_CONFIGFS=y

          # USB Gadget / ConfigFS
          CONFIG_USB_GADGET=y
          CONFIG_USB_CONFIGFS=y
          CONFIG_USB_CONFIGFS_F_HID=y
          CONFIG_USB_CONFIGFS_ECM_SUBSET=y
          CONFIG_USB_CONFIGFS_F_LB_SS=y
          CONFIG_USB_CONFIGFS_F_PRINTER=y
          CONFIG_USB_CONFIGFS_F_UAC1=y
          CONFIG_USB_CONFIGFS_F_UAC1_LEGACY=y
          CONFIG_USB_CONFIGFS_OBEX=y

          # USB HID Gadget
          CONFIG_USB_F_HID=y
          CONFIG_USB_HID=y
          CONFIG_HID_GADGET=y

          # RTL8188CUS / rtl8xxxu
          CONFIG_RTL8XXXU=y
          CONFIG_RTL8XXXU_UNTESTED=y

          # Wi-Fi / Wireless stack
          CONFIG_WLAN=y
          CONFIG_CFG80211=y
          CONFIG_MAC80211=y
          CONFIG_WEXT_CORE=y
          CONFIG_WEXT_PROC=y
          CONFIG_WEXT_SPY=y
          CONFIG_WEXT_PRIV=y
